"""Tiny behavior-cloning warm start generated by the exact BFS oracle."""

from __future__ import annotations

import random
import time
from dataclasses import asdict, dataclass
from typing import Any

import torch
from torch import nn

from .environment import ACTIONS, Puzzle, transition_state
from .model import TinyCausalPolicy
from .tokenizer import SokobanTokenizer


@dataclass(frozen=True)
class SFTConfig:
    max_puzzle_steps: int = 6
    epochs: int = 30
    batch_size: int = 128
    learning_rate: float = 1e-3
    weight_decay: float = 0.0
    gradient_clip: float = 1.0


@dataclass(frozen=True)
class SFTExample:
    input_ids: tuple[int, ...]
    action_index: int
    puzzle_id: str


def build_sft_examples(
    puzzles: list[Puzzle] | tuple[Puzzle, ...],
    tokenizer: SokobanTokenizer,
    *,
    max_puzzle_steps: int,
) -> list[SFTExample]:
    """Collect oracle state-action pairs without crossing split boundaries."""

    allowed_initial_states = {
        (
            puzzle.initial_state.player,
            puzzle.initial_state.box,
            puzzle.initial_state.goal,
        )
        for puzzle in puzzles
    }
    examples: list[SFTExample] = []
    for puzzle in puzzles:
        if puzzle.optimal_steps > max_puzzle_steps:
            continue
        state = puzzle.initial_state
        history: list[str] = []
        for action in puzzle.optimal_actions:
            key = state.player, state.box, state.goal
            if key in allowed_initial_states:
                examples.append(
                    SFTExample(
                        input_ids=tuple(tokenizer.encode(state, history)),
                        action_index=ACTIONS.index(action),
                        puzzle_id=puzzle.puzzle_id,
                    )
                )
            state, valid, _ = transition_state(state, action)
            if not valid:
                raise RuntimeError(f"BFS emitted invalid action for {puzzle.puzzle_id}")
            history.append(action)
    if not examples:
        raise RuntimeError("SFT generator produced no examples")
    return examples


def train_sft(
    model: TinyCausalPolicy,
    examples: list[SFTExample],
    tokenizer: SokobanTokenizer,
    *,
    config: SFTConfig,
    device: str | torch.device,
    seed: int,
) -> dict[str, Any]:
    device = torch.device(device)
    model.train()
    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=config.learning_rate,
        weight_decay=config.weight_decay,
    )
    generator = random.Random(seed + 4241)
    history: list[dict[str, float | int]] = []
    started = time.perf_counter()
    for epoch in range(1, config.epochs + 1):
        order = list(range(len(examples)))
        generator.shuffle(order)
        total_loss = 0.0
        total_correct = 0
        total_count = 0
        for start in range(0, len(order), config.batch_size):
            indices = order[start : start + config.batch_size]
            batch_examples = [examples[index] for index in indices]
            batch = tokenizer.pad_batch(
                [list(example.input_ids) for example in batch_examples],
                device=device,
            )
            labels = torch.tensor(
                [example.action_index for example in batch_examples],
                dtype=torch.long,
                device=device,
            )
            logits = model(batch.input_ids, batch.attention_mask)
            loss = nn.functional.cross_entropy(logits, labels)
            optimizer.zero_grad(set_to_none=True)
            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), config.gradient_clip)
            optimizer.step()
            total_loss += float(loss.detach().cpu().item()) * len(indices)
            total_correct += int((logits.argmax(dim=-1) == labels).sum().item())
            total_count += len(indices)
        history.append(
            {
                "epoch": epoch,
                "loss": total_loss / total_count,
                "action_accuracy": total_correct / total_count,
            }
        )
    return {
        "runtime_seconds": time.perf_counter() - started,
        "examples": len(examples),
        "config": asdict(config),
        "history": history,
    }
